# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  # 支持手动触发部署
  workflow_dispatch:
  # 当推送到 main 分支时自动部署
  push:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
          cache: "pnpm"

      # 检查是否存在 pnpm-lock.yaml，如果存在则安装 pnpm 并使用 pnpm，否则使用 npm
      - name: Install pnpm
        if: steps.check-files.outputs.has-pnpm-lock == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 安装项目依赖
      - name: Install dependencies
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm install
          else
            npm install
          fi

      # 构建项目
      - name: Build project
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm build
          else
            npm run build
          fi

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
